package main.java.com.command.board;

public class commandasdasdasd {
	-- 전체 중 날짜 검색과 닉네임 검색이 있는 경우 (EMPATH)- page
	SELECT * FROM
	(SELECT ROWNUM AS NO, t.* FROM 
	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM
	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YYYMMDD'), 'YYYMMDD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p
	JOIN MM_TABLE m ON p.WRITER = m.MM_ID
	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID
	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID
	WHERE T >= '2020-11-08' AND T <= '2020-11-10' AND NICKNAME = 'admin'
	ORDER BY EMPATHIZE_CNT DESC, REGDATE DESC, VIEWCNT DESC) t)
	WHERE NO >= 1 AND NO <= 10;

	-- search 가 있어 그냥 모든 데이터 반환 하는 경우 (EMPATH) (날짜 검색 + 닉네임 + 데이터를 반환해서 text 화 시켜서 검색해야 하는 경우)
	SELECT * FROM 
	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM
	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YYYMMDD'), 'YYYMMDD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p
	JOIN MM_TABLE m ON p.WRITER = m.MM_ID
	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID
	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID
	WHERE T >= '2020-11-08' AND T <= '2020-11-10' AND NICKNAME = 'admin'
	ORDER BY EMPATHIZE_CNT DESC, REGDATE DESC, VIEWCNT DESC);

	-- 전체 중 날짜 검색이 있는  경우 (EMPATH)- page
	SELECT * FROM
	(SELECT ROWNUM AS NO, t.* FROM 
	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM
	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YYYMMDD'), 'YYYMMDD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p
	JOIN MM_TABLE m ON p.WRITER = m.MM_ID
	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID
	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID
	WHERE T >= '2020-11-08' AND T <= '2020-11-10'
	ORDER BY EMPATHIZE_CNT DESC, REGDATE DESC, VIEWCNT DESC) t)
	WHERE NO >= 1 AND NO <= 10;

	-- search 가 있어 그냥 모든 데이터 반환 하는 경우 (EMPATH) (날짜 검색 + 데이터를 반환해서 text 화 시켜서 검색해야 하는 경우)
	SELECT * FROM 
	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM
	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YYYMMDD'), 'YYYMMDD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p
	JOIN MM_TABLE m ON p.WRITER = m.MM_ID
	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID
	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID
	WHERE T >= '2020-11-08' AND T <= '2020-11-10'
	ORDER BY EMPATHIZE_CNT DESC, REGDATE DESC, VIEWCNT DESC);


	------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

	-- 전체 중 날짜 검색과 닉네임 검색이 있는 경우 (VIEWCNT)- page
	SELECT * FROM
	(SELECT ROWNUM AS NO, t.* FROM 
	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM
	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YYYMMDD'), 'YYYMMDD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p
	JOIN MM_TABLE m ON p.WRITER = m.MM_ID
	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID
	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID
	WHERE T >= '2020-11-08' AND T <= '2020-11-10' AND NICKNAME = 'admin'
	ORDER BY VIEWCNT DESC, REGDATE DESC, EMPATHIZE_CNT DESC) t)
	WHERE NO >= 1 AND NO <= 10;

	-- search 가 있어 그냥 모든 데이터 반환 하는 경우 (VIEWCNT) (날짜 검색 + 닉네임 + 데이터를 반환해서 text 화 시켜서 검색해야 하는 경우)
	SELECT * FROM 
	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM
	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YYYMMDD'), 'YYYMMDD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p
	JOIN MM_TABLE m ON p.WRITER = m.MM_ID
	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID
	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID
	WHERE T >= '2020-11-08' AND T <= '2020-11-10' AND NICKNAME = 'admin'
	ORDER BY VIEWCNT DESC, REGDATE DESC, EMPATHIZE_CNT DESC);

	-- 전체 중 날짜 검색이 있는 경우 (VIEWCNT)- page
	SELECT * FROM
	(SELECT ROWNUM AS NO, t.* FROM 
	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM
	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YYYMMDD'), 'YYYMMDD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p
	JOIN MM_TABLE m ON p.WRITER = m.MM_ID
	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID
	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID
	WHERE T >= '2020-11-08' AND T <= '2020-11-10'
	ORDER BY VIEWCNT DESC, REGDATE DESC, EMPATHIZE_CNT DESC) t)
	WHERE NO >= 1 AND NO <= 10;

	-- search 가 있어 그냥 모든 데이터 반환 하는 경우 (VIEWCNT) (날짜 검색  + 데이터를 반환해서 text 화 시켜서 검색해야 하는 경우)
	SELECT * FROM 
	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM
	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YYYMMDD'), 'YYYMMDD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE) p
	JOIN MM_TABLE m ON p.WRITER = m.MM_ID
	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID
	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID
	WHERE T >= '2020-11-08' AND T <= '2020-11-10'
	ORDER BY VIEWCNT DESC, REGDATE DESC, EMPATHIZE_CNT DESC);

	--------------------------------------------------------------------------------------------------------------------------------------------------------

	-- 카테코리 중 날짜 검색과 닉네임 검색이 있는 경우 (CATEGORY)- page
	SELECT * FROM
	(SELECT ROWNUM AS NO, t.* FROM 
	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM
	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YYYMMDD'), 'YYYMMDD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE WHERE CATEGORY = 'MOVIE') p
	JOIN MM_TABLE m ON p.WRITER = m.MM_ID
	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID
	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID
	WHERE T >= '2020-11-08' AND T <= '2020-11-10' AND NICKNAME = 'admin'
	ORDER BY VIEWCNT DESC, REGDATE DESC, EMPATHIZE_CNT DESC) t)
	WHERE NO >= 1 AND NO <= 10;

	-- search 가 있어 그냥 모든 데이터 반환 하는 경우 (CATEGORY) (날짜 검색 + 닉네임 + 데이터를 반환해서 text 화 시켜서 검색해야 하는 경우)
	SELECT * FROM 
	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM
	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YYYMMDD'), 'YYYMMDD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE WHERE CATEGORY = 'MOVIE') p
	JOIN MM_TABLE m ON p.WRITER = m.MM_ID
	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID
	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID
	WHERE T >= '2020-11-08' AND T <= '2020-11-10' AND NICKNAME = 'admin'
	ORDER BY VIEWCNT DESC, REGDATE DESC, EMPATHIZE_CNT DESC);

	-- 전체 중 날짜 검색이 있는 경우 (CATEGORY)- page
	SELECT * FROM
	(SELECT ROWNUM AS NO, t.* FROM 
	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM
	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YYYMMDD'), 'YYYMMDD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE WHERE CATEGORY = 'MOVIE') p
	JOIN MM_TABLE m ON p.WRITER = m.MM_ID
	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID
	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID
	WHERE T >= '2020-11-08' AND T <= '2020-11-10'
	ORDER BY VIEWCNT DESC, REGDATE DESC, EMPATHIZE_CNT DESC) t)
	WHERE NO >= 1 AND NO <= 10;

	-- search 가 있어 그냥 모든 데이터 반환 하는 경우 (CATEGORY) (날짜 검색  + 데이터를 반환해서 text 화 시켜서 검색해야 하는 경우)
	SELECT * FROM 
	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM
	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YYYMMDD'), 'YYYMMDD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE WHERE CATEGORY = 'MOVIE') p
	JOIN MM_TABLE m ON p.WRITER = m.MM_ID
	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID
	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID
	WHERE T >= '2020-11-08' AND T <= '2020-11-10'
	ORDER BY VIEWCNT DESC, REGDATE DESC, EMPATHIZE_CNT DESC);

	-------------------------------------------------------------------------------------------------------------------------------------
	-- 내가쓴글 + 날짜 검색 + page
	SELECT * FROM
	(SELECT ROWNUM AS NO, t.* FROM 
	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM
	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YYYMMDD'), 'YYYMMDD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE WHERE WRITER = 1) p
	JOIN MM_TABLE m ON p.WRITER = m.MM_ID
	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID
	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID
	WHERE T >= '2020-11-08' AND T <= '2020-11-10'
	ORDER BY VIEWCNT DESC, REGDATE DESC, EMPATHIZE_CNT DESC) t)
	WHERE NO >= 1 AND NO <= 10;

	-- 내가 쓴 글 전체글 목록 + 날자 검색
	SELECT * FROM 
	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM
	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YYYMMDD'), 'YYYMMDD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE WHERE WRITER = 1) p
	JOIN MM_TABLE m ON p.WRITER = m.MM_ID
	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID
	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID
	WHERE T >= '2020-11-08' AND T <= '2020-11-10'
	ORDER BY VIEWCNT DESC, REGDATE DESC, EMPATHIZE_CNT DESC);

	-- 내가쓴글  + page
	SELECT * FROM
	(SELECT ROWNUM AS NO, t.* FROM 
	(SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM
	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YYYMMDD'), 'YYYMMDD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE WHERE WRITER = 1) p
	JOIN MM_TABLE m ON p.WRITER = m.MM_ID
	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID
	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID
	ORDER BY REGDATE DESC, VIEWCNT DESC, EMPATHIZE_CNT DESC) t)
	WHERE NO >= 1 AND NO <= 10;

	-- 내가 쓴글 전체 목록 
	SELECT p.*, m.*, f.*, NVL(e.HIT, 0) AS EMPATHIZE_CNT FROM
	(SELECT POST_ID, TITLE, WRITER, CATEGORY, REGDATE, to_date(to_char(regdate, 'YYYMMDD'), 'YYYMMDD') AS T, POST_CONTENTS, VIEWCNT FROM POST_TABLE WHERE WRITER = 1) p
	JOIN MM_TABLE m ON p.WRITER = m.MM_ID
	JOIN FILE_TABLE f ON p.POST_CONTENTS = f.FILE_ID
	LEFT JOIN (SELECT COUNT(*) AS HIT, POST_ID FROM EMPATHIZE_TABLE GROUP BY POST_ID) e ON p.POST_ID = e.POST_ID
	ORDER BY REGDATE DESC, VIEWCNT DESC, EMPATHIZE_CNT DESC;
}
